<?php

namespace CategoryBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;
use MainBundle\Entity\User;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
