<?php

namespace CategoryBundle\Repository;
use Doctrine\ORM\EntityManager;
use MainBundle\Entity\User;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepositoryService
{
    private $_em;

    public function __construct(EntityManager $em)
    {
        $this->_em = $em;
    }

    public function getAllUserIncomeCategories(User $user)
    {
        $repository = $this->_em->getRepository('CategoryBundle:Category');
        $query = $repository->createQueryBuilder('c')
            ->orderBy('c.name', 'ASC')
            ->where('c.user = :user')
            ->orWhere('c.user is null')
            ->andWhere('c.type = :income')
            ->orWhere('c.type is null')
            ->andWhere('c.valid = true')
            ->setParameter('user', $user)
            ->setParameter('income','income');

        $income = $query->getQuery()->getResult();

        return $income;
    }

    public function getAllUserExpenseCategories(User $user)
    {
        $repository = $this->_em->getRepository('CategoryBundle:Category');
        $query = $repository->createQueryBuilder('c')
            ->orderBy('c.name', 'ASC')
            ->where('c.user = :user')
            ->orWhere('c.user is null')
            ->andWhere('c.type = :expense')
            ->orWhere('c.type is null')
            ->andWhere('c.valid = true')
            ->setParameter('user', $user)
            ->setParameter('expense','expense');

        $expense = $query->getQuery()->getResult();

        return $expense;
    }
}
