category:
    resource: "@CategoryBundle/Controller/"
    type:     annotation
    prefix:   /

budget:
    resource: "@BudgetBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"