services:
    helper.datetime:
        class: BudgetBundle\Helper\DateTime\DateTimeHelper

    budget.repository.budget:
        class: BudgetBundle\Repository\BudgetRepositoryService
        arguments:
          - '@doctrine'
          - '@helper.datetime'

    budget.entity.form:
        class: BudgetBundle\Form\Services\BudgetFormService
        arguments:
          - '@service_container'

    budget.money.counter:
        class: BudgetBundle\Helper\BudgetMoneyCounter

    budget.request.budgetbydaterange:
        class: BudgetBundle\Helper\Request\BudgetByDateRangeRequest
        arguments: ['@helper.datetime']
        calls:
          - [setRequest, ["@request_stack"]]


