services:
    helper.datetime:
        class: BudgetBundle\Helper\DateTime\DateTimeHelper

    budget.repository.budget:
        class: BudgetBundle\Repository\BudgetRepositoryService
        arguments:
          - '@doctrine'
          - '@helper.datetime'

    budget.entity.form:
        class: BudgetBundle\Form\Services\BudgetFormService
        arguments:
          - '@service_container'

    budget.money.counter:
        class: BudgetBundle\Helper\BudgetMoneyCounter

    budget.request.daterange:
        class: BudgetBundle\Helper\Request\BudgetDateRangeRequest
        arguments: ['@helper.datetime']
        calls:
          - [setRequest, ["@request_stack"]]

    budget.request.budgetbydaterange:
        class: BudgetBundle\Helper\Request\BudgetDateRangeRequest
        arguments: ['@helper.datetime']
        calls:
          - [setRequest, ["@request_stack"]]

    income.category.repository:
        class: BudgetBundle\Repository\BudgetCategoryRepository
        arguments:
          - '@doctrine'
          - 'income'

    expense.category.repository:
        class: BudgetBundle\Repository\BudgetCategoryRepository
        arguments:
          - '@doctrine'
          - 'expense'

    budget.expense.preview:
        class: BudgetBundle\Entity\BudgetPreview
        arguments:
          - '@expense.category.repository'
          - "@=service('doctrine.orm.entity_manager').getRepository('BudgetBundle:Expenses')"
          - '@budget.money.counter'

    budget.income.preview:
        class: BudgetBundle\Entity\BudgetPreview
        arguments:
          - '@income.category.repository'
          - "@=service('doctrine.orm.entity_manager').getRepository('BudgetBundle:Income')"
          - '@budget.money.counter'
